### PR TITLE
fix image issues

### PR DESCRIPTION
**Pull request by vwxyzjn**
Thanks @liutianlin0121 for the repo!!! CC @lvwerra

This PR makes the images more readable. I followed https://iclr-blogposts.github.io/2024/blog/distill-example/ to make the images wider. 

image

image

Also fixes some minor bibtex issues!

### CODE REVIEW

**Comment by liutianlin0121** [comment]
Thanks a lot!

**Comment by liutianlin0121** [comment]
@vwxyzjn @lvwerra Shall I submit an abstract registration? The abstract ddl is next Monday (Nov 06 2023 UTC-0).

**Comment by vwxyzjn** [comment]
Feel free to :) my openreivew account is sh3397@drexel.edu.

**Comment by vwxyzjn** [comment]
@lvwerra's account is [leandro@huggingface.co](mailto:leandro@huggingface.co)

**Comment by liutianlin0121** [comment]
Just submitted the abstract on openreview. Feel free to edit! We are the 2nd submitted abstract :-) I'll go over the main text again next weekend.

**Comment by liutianlin0121** [comment]
Hi both! I anonymized the github repo link and removed links that cannot be easily anonymized (like wandb logs and huggingface demo) from the blog. Could you give it a pass? 

If everything looks fine, I can submit it soon. We've got some extra time since the full-blog submission deadline has been updated to December 17th, so no rush! 😊

**Comment by liutianlin0121** [comment]
Hi both! @vwxyzjn @lvwerra If it is OK for you, I plan to submit our blog Friday this week (the deadline is on Sunday).

**Comment by vwxyzjn** [comment]
Hi @liutianlin0121 thanks for preparing the blog post! I will check it out today.

**Pull request merged**
